kind: Deployment
apiVersion: apps/v1
metadata:
  name: infraweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infraweb
  template:
    metadata:
      name: infraweb
      labels:
        app: infraweb
    spec:      
      containers:
      - name: infraweb
        env:
        - name: ApiAddress
          value: http://infraapi-service:5000/WeatherForecast
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: 1234567890.dkr.ecr.us-east-1.amazonaws.com/infraweb:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        resources: {}