apiVersion: v1
kind: Service
metadata:
  name: infraweb-service
  labels:
    app: infraweb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: infraweb
  ports:
  - protocol: TCP
    name: ui
    port: 80
    targetPort: 5000
